---
configuration:
   namespace:                     "tsl"
   header_file_extension:         ".hpp"
   source_file_extension:         ".cpp"
   root_path:                     "./generated_tsl"
   compiler_architecture_prefix:  "-m"
   use_concepts:                  True
   emit_workaround_warnings:      True
   relevant_types:                 ["uint8_t", "int8_t", "uint16_t", "int16_t", "uint32_t", "int32_t", "uint64_t", "int64_t", "float", "double"]
   always_required_primitives:     ["allocate","deallocate","allocate_aligned","memory_cp","set"]
   library:
      root_path:                  "include"
      top_level_header_fname:     "tslintrin"
      static_files:
         root_path:               "static"
      hardware_specific_files:
         top_level_header_fname:  "tsl_generated"
         root_path:               "generated"
         extensions:              "extensions"
         primitive_declarations:  "declarations"
         primitive_definitions:   "definitions"
   silent_warnings:               ["-Wno-ignored-attributes", "-Wno-attributes"]
   expansions:
      cmake:
         enabled:                 True
         minimum_version:         "3.10"
         verbose_make_files:      True
         tsl_lib_name:            "tsl"
      unit_tests:
         enabled:                 True
         namespace:               "testing"
         root_path:               "src/test"
         test_header_url:         "https://github.com/catchorg/Catch2/releases/download/v2.13.9/catch.hpp"
         draw_dependency_graph:   True
         static_files:
            root_path:            "generator/static_files/expansions/tests"
      readme_md:
         enabled:                 False
         root_path:               "./"
configuration_files:
   log_config_file:               "generator/config/log_conf.yaml"
   schema_file:                   "generator/config/generator/tsl_generator_schema.yaml"
   jinja_templates:
      root_path:                  "generator/config/generator/tsl_templates"
   primitive_data:
      root_path:                  "primitive_data"
      extensions_path:            "extensions"
      primitives_path:            "primitives"
   static_files:
      root_path:                  "generator/static_files"
      lib:                        "core"
   supplementary:
      root_path:                  "supplementary"
...
