name: Generating with py3.8-12
run-name: Generates with py3.8-3.12

on:
  workflow_run:
    workflows: [Generating with py3.8-3.12]
    types:
      - completed

jobs:
  check-generation:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: validate-tsl.yml
          name: python_generation_failed
          path: ${{ github.workspace }}/status
          if_no_artifact_found: ignore
      - name: Fail on status existing
        run: |
          if [ -f ${{ github.workspace }}/status/python_generation_failed ]; then
            echo "Generation failed"
            exit 1
          fi
  everything-fine:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Everything is fine
        run: echo "Everything is fine"