name: 'tvl-generate-build'

on: ['workflow_call']

permissions:
  contents: read

jobs:
  validate:
    uses: ./.github/workflows/test_tvlgen.yml
  build:
    runs-on: ubuntu-latest
    needs: validate
    steps:
    - name: 'Generate TVL'
      run: |
        cmake -B tvl
    - name: 'Build TVL'
      run: |
        make -C tvl
    - name: 'Run Tests'
      run: |
        ./tvl/tvl/generator_output/src/test/tvl_test