name: 'tsl-push'

on:
  push:
    branches: ['main']

permissions:
  contents: write

jobs:
  validate-and-build:
    uses: ./.github/workflows/generate_build_tsl.yml
  update-readme:
    runs-on: ubuntu-latest
    needs: validate-and-build
    steps:
    - name: 'Loads State'
      uses: actions/cache/restore@v3
      with:
        path: ./
        key: ${{ runner.os }}}-${{ env.GITHUB_SHA }}-checked-out
    - name: Setup Git Creds
      run: |
        git reset --hard
        git config --global user.email "johannes.pietrzyk@tu-dresden.de"
        git config --global user.name "GitHub Action (Maintainer: Johannes Pietrzyk)"
        python3 main.py --generate-readme-files --generate-readme-files
        git commit -a -m "Updated Readmes"
        git push