name: 'tsl-validate-pr'

on:
  pull_request:
    branches: ['main']
    types: ['opened', 'reopened']

permissions:
  contents: read

jobs:
  validate-and-build:
    uses: ./.github/workflows/generate_build_tsl.yml
    with:
      checkout_ref: ${{ github.event.pull_request.head.sha }}