name: Validate TVL Generator

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout TVL repository (recursive)
      uses: actions/checkout@v3
      with:
        repository: db-tu-dresden/TVLGen.git
        ref: main
        token: '${{ secrets.DHTVL_AT }}'
        submodules: recursive
    - name: Setup Git Creds
      run: |
        git config --global user.email "johannes.pietrzyk@tu-dresden.de"
        git config --global user.name "GitHub Action (Maintainer: Johannes Pietrzyk)"
    - name: Set up Python 3.10.2
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.2"
    - name: Install generator dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f ./requirements.txt ]; then pip install -r ./requirements.txt; fi
    - name: Update TVL generator repository
      run: |
        git submodule foreach -q --recursive 'branch="$(git config -f $toplevel/.gitmodules submodule.$name.branch)"; git switch $branch'
        git add primitive_data
        git commit -m "Updated submodule primitive_data"
        python tvlgen.py -o ./lib -c config -d primitive_data
