name: Builds & run on x86
run-name: Builds on x86

on:
  workflow_run:
    workflows: [Build and test for Intel / ARM]
    types:
      - completed

jobs:
  check-generation:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build-and-test.yml
          name: intel_bat_failed
          path: ${{ github.workspace }}/status
          if_no_artifact_found: ignore
      - name: Fail on status existing
        run: |
          found_file=false
          for file in ${{ github.workspace }}/status/intel_bat_failed*; do
            if [ -f $file ]; then
              found_file=true
              break
            fi
          done
          if $found_file; then
            echo "Generation failed"
            exit 1
          fi
  everything-fine:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Everything is fine
        run: echo "Everything is fine"